name: gracecityportland
favicon: null
layout_spectrum: 0.6239402922801673
typography_spectrum: 0.5648626547772437
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4145082454197109
  lightness: 0.6806434218306094
  saturation: 0.9368575755506754
  rhythmicContrast: 0.4822565095964819
purpose: []
